const nodemailer = require('nodemailer')

// Create transporter
const transporter = nodemailer.createTransport({
  host: process.env.EMAIL_HOST || 'smtp.zoho.in',
  port: parseInt(process.env.EMAIL_PORT || '465'),
  secure: process.env.EMAIL_SECURE === 'true',
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS
  },
  tls: {
    rejectUnauthorized: true
  }
})

async function sendEmail(to, summary, fileName) {
  const maxRetries = 3
  const retryDelays = [1000, 5000, 15000] // 1s, 5s, 15s
  
  const logEntry = {
    to,
    fileName,
    timestamp: new Date().toISOString(),
    attempts: 0
  }
  
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    logEntry.attempts = attempt + 1
    
    try {
      if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
        const error = 'Email credentials not configured'
        logEntry.status = 'failed'
        logEntry.error = error
        console.error('❌ Email delivery failed:', JSON.stringify(logEntry, null, 2))
        return { success: false, error, log: logEntry }
      }

      const mailOptions = {
        from: `"Rabbitt AI" <${process.env.EMAIL_USER}>`,
        to,
        subject: `Sales Analysis Summary - ${fileName}`,
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
            <h1 style="color: #4F46E5; border-bottom: 3px solid #4F46E5; padding-bottom: 10px;">
              Sales Analysis Summary
            </h1>
            <p style="color: #6B7280; font-size: 14px;">
              Generated by Rabbitt AI for <strong>${fileName}</strong>
            </p>
            <hr style="border: 1px solid #E5E7EB; margin: 20px 0;">
            <div style="white-space: pre-wrap; line-height: 1.8; color: #374151; font-size: 15px;">
              ${summary.replace(/\n/g, '<br>')}
            </div>
            <hr style="border: 1px solid #E5E7EB; margin: 20px 0;">
            <p style="color: #9CA3AF; font-size: 12px; text-align: center;">
              This email was automatically generated by Rabbitt AI Sales Insight Automator.
            </p>
          </div>
        `
      }

      const info = await transporter.sendMail(mailOptions)
      
      logEntry.status = 'sent'
      logEntry.messageId = info.messageId
      logEntry.response = info.response
      
      console.log('✅ Email delivery successful:', JSON.stringify(logEntry, null, 2))
      
      return { success: true, messageId: info.messageId, log: logEntry }
      
    } catch (error) {
      const isRetryable = error.code === 'ECONNECTION' || 
                          error.code === 'ETIMEDOUT' || 
                          error.code === 'ECONNREFUSED'
      
      if (isRetryable && attempt < maxRetries) {
        const delay = retryDelays[attempt]
        console.warn(`⚠️ Email send failed (attempt ${attempt + 1}/${maxRetries + 1}), retrying in ${delay}ms...`)
        logEntry.lastError = error.message
        await new Promise(resolve => setTimeout(resolve, delay))
        continue
      }
      
      logEntry.status = 'failed'
      logEntry.error = error.message
      logEntry.errorCode = error.code
      
      console.error('❌ Email delivery failed:', JSON.stringify(logEntry, null, 2))
      
      return { success: false, error: error.message, log: logEntry }
    }
  }
  
  // Should never reach here, but just in case
  logEntry.status = 'failed'
  logEntry.error = 'Max retries exceeded'
  console.error('❌ Email delivery failed:', JSON.stringify(logEntry, null, 2))
  return { success: false, error: 'Max retries exceeded', log: logEntry }
}

module.exports = { sendEmail }
