import nodemailer from 'nodemailer'
import { config } from '../config/env'

class EmailService {
  private transporter: nodemailer.Transporter

  constructor() {
    this.transporter = nodemailer.createTransport({
      host: config.email.host,
      port: config.email.port,
      secure: config.email.secure,
      auth: {
        user: config.email.user,
        pass: config.email.pass,
      },
    })
  }

  async sendSummary(to: string, summary: string, fileName: string): Promise<void> {
    const mailOptions = {
      from: `"Rabbitt AI" <${config.email.user}>`,
      to,
      subject: `Sales Analysis Summary - ${fileName}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h1 style="color: #4F46E5;">Sales Analysis Summary</h1>
          <p style="color: #6B7280;">Generated by Rabbitt AI for <strong>${fileName}</strong></p>
          <hr style="border: 1px solid #E5E7EB; margin: 20px 0;">
          <div style="white-space: pre-wrap; line-height: 1.6; color: #374151;">
            ${summary.replace(/\n/g, '<br>')}
          </div>
          <hr style="border: 1px solid #E5E7EB; margin: 20px 0;">
          <p style="color: #9CA3AF; font-size: 12px;">
            This email was automatically generated by Rabbitt AI Sales Insight Automator.
          </p>
        </div>
      `,
    }

    await this.transporter.sendMail(mailOptions)
  }
}

export const emailService = new EmailService()
